version: '3.8'

# This file defines all the services we need for local development
# Run: docker-compose up -d

services:
  # PostgreSQL - Our main database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: prpilot
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: prpilot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # TODO: We'll add pgvector extension later for semantic search

  # Redis - Message queue for Celery
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  # Backend - FastAPI webhook server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://prpilot:devpassword@postgres:5432/prpilot
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  
  # Worker - Celery background tasks
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://prpilot:devpassword@postgres:5432/prpilot
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./worker:/app
    command: celery -A tasks worker --loglevel=info

volumes:
  postgres_data:
  redis_data:

